name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  workflow_dispatch: {}

jobs:
  race-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export constant environmental variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .github/constants.env

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true

      - name: Ensure main package builds
        run: |
          go build

      - name: Run tests
        run: |
          go test -race -timeout 5m -v ./...

  fuzz:
    runs-on: ubuntu-latest
    needs: race-test
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export constant environmental variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .github/constants.env

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true

      - name: Fuzz code for 10 minutes
        run: |
          go test -fuzz Fuzz -run DONOT -fuzztime 10m

  build-image:
    runs-on: ubuntu-latest
    # only run this check on pull requests, pushes to master will trigger
    # an image release
    if: contains(github.ref, 'pull')
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker image builds
        uses: docker/build-push-action@v4
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:build-test
